# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

require 'dotenv/load'

default_platform(:ios)

# bundle exec fastlane ios beta
platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    app_store_connect_api_key_path = ENV['APP_STORE_CONNECT_API_KEY_PATH']
    build_app(scheme: "iosApp", xcargs: "-allowProvisioningUpdates")
    upload_to_testflight(api_key_path: app_store_connect_api_key_path)
  end

  desc "Push a new beta build to public TestFlight"
  lane :beta_public do
    app_store_connect_api_key_path = ENV['APP_STORE_CONNECT_API_KEY_PATH']
    build_app(scheme: "iosApp", xcargs: "-allowProvisioningUpdates")
    upload_to_testflight(
      api_key_path: app_store_connect_api_key_path,
      groups: ["Wally iOS Beta"]
    )
  end
end
